version: '3.8'

services:
  questdb:
    image: questdb/questdb:latest
    ports:
      - "9000:9000"   # Web UI
      - "8812:8812"   # PostgreSQL wire protocol
    volumes:
      - ./data:/var/lib/questdb/db
